data = [
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 30,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 30,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 50,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 50,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 70,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 70,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 90,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Marvel",
    Technolgiestufe: 90,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 30,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 30,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 50,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 50,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 70,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 70,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 90,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Phonak",
    Modell: "Audeo Paradise",
    Technolgiestufe: 90,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 30,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 30,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 70,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 70,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 90,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Paradise",
    Technolgiestufe: 90,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 30,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 30,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 70,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 70,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 90,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Phonak",
    Modell: "Bolero Marvel",
    Technolgiestufe: 90,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Marvel",
    Technolgiestufe: 30,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Marvel",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Marvel",
    Technolgiestufe: 70,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Phonak",
    Modell: "Naida Marvel",
    Technolgiestufe: 90,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Phonak",
    Modell: "Lyric",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Phonak",
    Modell: "Virto Marvel Titanium",
    Technolgiestufe: 70,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Phonak",
    Modell: "Virto Marvel Titanium",
    Technolgiestufe: 90,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Phonak",
    Modell: "Virto Marvel",
    Technolgiestufe: 30,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Phonak",
    Modell: "Virto Marvel",
    Technolgiestufe: 50,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Phonak",
    Modell: "Virto Marvel",
    Technolgiestufe: 70,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Phonak",
    Modell: "Virto Marvel",
    Technolgiestufe: 90,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Oticon",
    Modell: "Ruby",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Oticon",
    Modell: "Ruby",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Oticon",
    Modell: "Ruby",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Oticon",
    Modell: "Ruby",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn S",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn S",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn S",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn S",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn S",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn S",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Oticon",
    Modell: "More",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Oticon",
    Modell: "More",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Oticon",
    Modell: "More",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn",
    Technolgiestufe: 1,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn",
    Technolgiestufe: 2,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Oticon",
    Modell: "Opn",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Oticon",
    Modell: "Xceed",
    Technolgiestufe: 1,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Oticon",
    Modell: "Xceed",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Oticon",
    Modell: "Xceed",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Oticon",
    Modell: "Siya",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Oticon",
    Modell: "Siya",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "Edge AI 2400",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "Edge AI 2400",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "Edge AI 2400",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "Edge AI 2400",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "Edge AI 2400",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 1890,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 2000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 2000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 2000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 2000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 2000",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1600",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1600",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1600",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1600",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1600",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1200",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1200",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1200",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1200",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1200",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1200,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 740,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1200,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 840,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1200,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 740,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1200,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 840,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1200,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 940,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: "AI 1000",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1000,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1000,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1000,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1000,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Livio",
    Technolgiestufe: 1000,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Starkey",
    Modell: "Soundlens Synergy",
    Technolgiestufe: "iQ i2400",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Soundlens Synergy",
    Technolgiestufe: "iQ i2000",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Starkey",
    Modell: "Soundlens Synergy",
    Technolgiestufe: "iQ i1600",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i2400",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i2400",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i2400",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i2000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i2000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i2000",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1600",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1600",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1600",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1200",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1200",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1200",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "iQ i1000",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "i1000",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "i1000",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Starkey",
    Modell: "Muse",
    Technolgiestufe: "i1000",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 4,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 4,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 4,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 4,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 2,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "ReSound",
    Modell: "Key",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "ReSound",
    Modell: "One",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "ReSound",
    Modell: "One",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "ReSound",
    Modell: "One",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "ReSound",
    Modell: "One",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "ReSound",
    Modell: "One",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "ReSound",
    Modell: "One",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "ReSound",
    Modell: "One M&RIE",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1790,
  },
  {
    Hersteller: "ReSound",
    Modell: "One M&RIE",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1890,
  },
  {
    Hersteller: "ReSound",
    Modell: "One M&RIE",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "ReSound",
    Modell: "One M&RIE",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 9,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "ReSound",
    Modell: "LiNX Quattro",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1700,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1200,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 750,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1700,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1200,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 750,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 9,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1700,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1200,
  },
  {
    Hersteller: "ReSound",
    Modell: "Linx 3D",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 750,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enzo",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1600,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enzo",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1100,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enzo",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enya",
    Technolgiestufe: 4,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 865,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enya",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 830,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enya",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enya",
    Technolgiestufe: 4,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 865,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enya",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 830,
  },
  {
    Hersteller: "ReSound",
    Modell: "Enya",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Signia",
    Modell: "Styletto X",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 2240,
  },
  {
    Hersteller: "Signia",
    Modell: "Styletto X",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Signia",
    Modell: "Styletto X",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1240,
  },
  {
    Hersteller: "Signia",
    Modell: "Styletto X",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 940,
  },
  {
    Hersteller: "Signia",
    Modell: "Styletto X",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Silk X",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1990,
  },
  {
    Hersteller: "Signia",
    Modell: "Silk X",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Signia",
    Modell: "Silk X",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Signia",
    Modell: "Silk X",
    Technolgiestufe: 2,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Signia",
    Modell: "Silk X",
    Technolgiestufe: 1,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Signia",
    Modell: "Insio Nx",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1990,
  },
  {
    Hersteller: "Signia",
    Modell: "Insio Nx",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Signia",
    Modell: "Insio Nx",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Signia",
    Modell: "Insio Nx",
    Technolgiestufe: 2,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Insio Nx",
    Technolgiestufe: 1,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Signia",
    Modell: "Intuis",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Signia",
    Modell: "Intuis",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Signia",
    Modell: "Intuis",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion Nx",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1990,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion Nx",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion Nx",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion Nx",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion Nx",
    Technolgiestufe: 1,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion X",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 2190,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion X",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion X",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion X",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Signia",
    Modell: "Motion X",
    Technolgiestufe: 1,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Prompt",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Signia",
    Modell: "Active",
    Technolgiestufe: "Active Pro",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 1195,
  },
  {
    Hersteller: "Signia",
    Modell: "Active",
    Technolgiestufe: "Active",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Akku",
    Preis: 825,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure Nx",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1990,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure Nx",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure Nx",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure Nx",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure Nx",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1990,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 2190,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure X",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure AX",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 2290,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure AX",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Signia",
    Modell: "Pure AX",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 440,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 440,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 440,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 440,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 330,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 330,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 330,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 330,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 220,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 220,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 220,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 220,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 110,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 110,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 110,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Moment",
    Technolgiestufe: 110,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 440,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 440,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 440,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 330,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 330,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 330,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 220,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 220,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 220,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 110,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 110,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Widex",
    Modell: "Evoke",
    Technolgiestufe: 110,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 100,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 100,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 100,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 100,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 50,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Widex",
    Modell: "Magnify",
    Technolgiestufe: 50,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 100,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 100,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 100,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 50,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 750,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 50,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 750,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 50,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 750,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 30,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 30,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Widex",
    Modell: "Enjoy",
    Technolgiestufe: 30,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Alpha",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Alpha",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Alpha",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Viron",
    Technolgiestufe: 1,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 9,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 1,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 1,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Zerena",
    Technolgiestufe: 1,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Leox",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Leox",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Saphira",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Saphira",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Saphira",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Saphira",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Saphira",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Saphira",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Nevara",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Nevara",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Nevara",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Supremia",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Bernafon",
    Modell: "Supremia",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Blu",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover Next",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover Next",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Discover Next",
    Technolgiestufe: 9,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Discover Next",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Discover Next",
    Technolgiestufe: 5,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Discover Next",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Discover",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Discover",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 690,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "Pro Fit",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "Pro Now",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "800 Fit",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "800 Now",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "700 Fit",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "700 Now",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "600 Fit",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Moxi Tempus",
    Technolgiestufe: "500 Fit",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Tempus",
    Technolgiestufe: "Pro",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Tempus",
    Technolgiestufe: 800,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Tempus",
    Technolgiestufe: 700,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Tempus",
    Technolgiestufe: 600,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Stride Tempus",
    Technolgiestufe: 500,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Max Tempus",
    Technolgiestufe: "Pro",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Max Tempus",
    Technolgiestufe: 800,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Max Tempus",
    Technolgiestufe: 700,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Max Tempus",
    Technolgiestufe: 600,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Max Tempus",
    Technolgiestufe: 500,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Tempus",
    Technolgiestufe: "Pro",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Tempus",
    Technolgiestufe: 800,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Tempus",
    Technolgiestufe: 700,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Tempus",
    Technolgiestufe: 600,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Unitron",
    Modell: "Insera Tempus",
    Technolgiestufe: 500,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Unitron",
    Modell: "Shine Rev +",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Unitron",
    Modell: "Shine Rev +",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Unitron",
    Modell: "Shine Rev +",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "quiX",
    Technolgiestufe: "G6 16",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Audio Service",
    Modell: "quiX",
    Technolgiestufe: "G6 12",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Audio Service",
    Modell: "quiX",
    Technolgiestufe: "G6 8",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "quiX",
    Technolgiestufe: "G6 6",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "quiX",
    Technolgiestufe: "G6 4",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Stiline",
    Technolgiestufe: "G6 16",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Stiline",
    Technolgiestufe: "G6 12",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Stiline",
    Technolgiestufe: "G6 8",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Stiline",
    Technolgiestufe: "G6 6",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Stiline",
    Technolgiestufe: "G6 4",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 16",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 12",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 8",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 6",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 4",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 16",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1490,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 12",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 8",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 6",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Mood",
    Technolgiestufe: "G6 4",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Duo",
    Technolgiestufe: "G6 16",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Duo",
    Technolgiestufe: "G6 12",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Duo",
    Technolgiestufe: "G6 8",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Duo",
    Technolgiestufe: "G6 6",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Duo",
    Technolgiestufe: "G6 4",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Power HdO",
    Technolgiestufe: "G6 16",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1590,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Power HdO",
    Technolgiestufe: "G6 12",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Power HdO",
    Technolgiestufe: "G6 8",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Power HdO",
    Technolgiestufe: "G6 6",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Power HdO",
    Technolgiestufe: "G6 4",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ida BT",
    Technolgiestufe: "G5 16",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ida BT",
    Technolgiestufe: "G5 12",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ida BT",
    Technolgiestufe: "G5 8",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ida BT",
    Technolgiestufe: "G5 6",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ida BT",
    Technolgiestufe: "G5 4",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ilea",
    Technolgiestufe: "G5 16",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ilea",
    Technolgiestufe: "G5 12",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ilea",
    Technolgiestufe: "G5 8",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ilea",
    Technolgiestufe: "G5 6",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Ilea",
    Technolgiestufe: "G5 4",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Icon",
    Technolgiestufe: "G5 16",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Icon",
    Technolgiestufe: "G5 12",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Icon",
    Technolgiestufe: "G5 8",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Icon",
    Technolgiestufe: "G5 6",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Icon",
    Technolgiestufe: "G5 4",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Rixx",
    Technolgiestufe: "G5 16",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Rixx",
    Technolgiestufe: "G5 12",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Rixx",
    Technolgiestufe: "G5 8",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Rixx",
    Technolgiestufe: "G5 6",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Rixx",
    Technolgiestufe: "G5 4",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Sun",
    Technolgiestufe: "G5 16",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Sun",
    Technolgiestufe: "G5 12",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Sun",
    Technolgiestufe: "G5 8",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Sun",
    Technolgiestufe: "G5 6",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Audio Service",
    Modell: "Sun",
    Technolgiestufe: "G5 4",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 6,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 6,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 6,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 6,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 4,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 4,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 4,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 4,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 2,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Interton",
    Modell: "Move",
    Technolgiestufe: 2,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 6,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 6,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 4,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 4,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 3,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 2,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Interton",
    Modell: "Ready",
    Technolgiestufe: 2,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 9030,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 9010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 9010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7030,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1290,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 5030,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 5010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 5010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 3010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 890,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 3010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 2010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 790,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 2010,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 9010,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7020,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7020,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1190,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7010,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 5010,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 3020,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 3020,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 3010,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 2010,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 690,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 9000,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 7000,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 5000,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 3000,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Philips",
    Modell: "Hearlink",
    Technolgiestufe: 2000,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 790,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1790,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1490,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1190,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Stratos",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound Excite Pro",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam Excite Pro",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jazz Excite Pro",
    Technolgiestufe: 9,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1690,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jazz Excite Pro",
    Technolgiestufe: 9,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1390,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jazz Excite Pro",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jazz Excite Pro",
    Technolgiestufe: 7,
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 9,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 7,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 5,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Sound SHD",
    Technolgiestufe: 3,
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1690,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1390,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 1090,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Akku",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Jam SHD",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Beat SHD",
    Technolgiestufe: 9,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1590,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Beat SHD",
    Technolgiestufe: 7,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 1290,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Beat SHD",
    Technolgiestufe: 5,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 990,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Beat SHD",
    Technolgiestufe: 3,
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 890,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Flow+",
    Bauform: "Hinter dem Ohr (HdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Flow+",
    Bauform: "Externer Hörer (RIC)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
  {
    Hersteller: "Hansaton",
    Modell: "Flow+",
    Bauform: "In dem Ohr (IdO)",
    Aufladbar: "Batterie",
    Preis: 700,
  },
];
